### PR TITLE
Add proper error messages for unsupported endpoints (q-m#16)

### LINKED ISSUE #16: Add unsupported endpoints
Not all scrapyd endpoints are supported, by design. Return a JSON error response, instead of 404 with HTML error page.

### PR DESCRIPTION
**Pull request by RuurdBijlsma-Ordina**
I used http status 501 (Not Implemented) for this, but if you think 404 is better, I'll change it.

I took the messages sent with the error from the README and added basic tests.

Fixes #16

### CODE REVIEW

**Comment by RuurdBijlsma-Ordina** [comment]
btw I wasn't 100% sure how to name the tests, or if they are even needed. I went with test_addversion, test_delversion, test_delproject

**Review by wvengen — APPROVED** [review]
Ah, super! Glad you were able to come up with a PR like this so fast, well done :rocket:
One thing you could improve: mention the issue number in the PR body, e.g. "Fixes #16".

**Comment by RuurdBijlsma-Ordina** [comment]
> Ah, super! Glad you were able to come up with a PR like this so fast, well done 🚀 One thing you could improve: mention the issue number in the PR body, e.g. "Fixes #16".

Ah yea will do for this one and coming ones, thanks.

**Comment by wvengen** [comment]
I'm doubting a bit between 404 and 501 as the http status. I think 501 fine, I'll accept it :)

**Pull request merged**
